import './global.css';
/**
 * Metadata configuration for the Next.js application.
 * This object defines various site-wide metadata, including
 * titles, descriptions, icons, social sharing information, and more.
 */
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: {
    icon: [
      { rel: "icon", url: "/favicon-48x48.png", sizes: "48x48" },
      { rel: "icon", url: "/favicon.svg", type: "image/svg+xml" },
      { rel: "shortcut icon", url: "/favicon.ico" },
    ],
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  applicationName: "ArejengRecipeApp",
  openGraph: {
    title: "Arejeng Recipe App",
    description: "Discover a variety of recipes with ArejengRecipeApp",
    // Uncomment and add the correct URL of the website if available
    // url: "https://mywebsite.com", 
    type: "website",
    images: [
      {
        // Uncomment and add the correct URL for the Open Graph image if available
        // url: "https://yourwebsite.com/og-image.jpg",
        width: 800,
        height: 600,
        alt: "Arejeng Recipe App",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@YourTwitterHandle",
    title: "Arejeng Recipe App",
    description: "Discover a variety of recipes with ArejengRecipeApp",
    image: "https://yourwebsite.com/twitter-image.jpg",
  },
  keywords: ["recipes", "cooking", "food", "ArejengRecipeApp"],
  author: "Name of author", // Add the name of the author here
};

/**
 * Viewport configuration for the Next.js application.
 * Moved the themeColor here as per the latest Next.js requirements.
 */
export const viewport = {
  themeColor: "#ffffff",
};

/**
 * Root layout component for the Next.js application.
 * This component wraps the entire app, providing the main HTML structure.
 *
 * @param {Object} props - The properties passed to the component.
 * @param {React.ReactNode} props.children - The nested content to render inside the layout.
 * @returns {JSX.Element} The RootLayout component.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
